---
name: Codeowners
on:
  push:
    branches:
      - master
    paths:
      - '*/*/metadata.xml'
jobs:
  codeowners:
    name: Codeowners
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          .scripts/generate-codeowners.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CODEOWNERS
          git commit -m 'codeowners: Update CODEOWNERS' || exit 0
          git push
