---
name: pkgcheck
on:
  push:
    paths:
      - '*/*/*.ebuild'
  pull_request:
    paths:
      - '*/*/*.ebuild'
jobs:
  pkgcheck:
    name: pkgcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pkgcore/pkgcheck-action@v1
        with:
          args: --keywords=-RedundantVersion
