---
name: Repoman
on:
  push:
    paths:
      - '*/*/*.ebuild'
  pull_request:
    paths:
      - '*/*/*.ebuild'
jobs:
  repoman:
    name: Repoman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gentoo-monero/repoman-action@v1
